# Generated by Django 3.2 on 2022-08-15 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200211_1303'),
        ('products', '0002_auto_20220805_1513'),
    ]

    operations = [
    ]
